from fpdf import FPDF
import datetime
import os
import uuid

class MedicalReport(FPDF):
    def header(self):
        # Professional Label
        self.set_font('Arial', 'B', 8)
        self.set_text_color(100)
        self.cell(0, 5, 'CONFIDENTIAL MEDICAL RECORD | FOR CLINICAL REVIEW', 0, 1, 'R')
        self.ln(5)

    def footer(self):
        self.set_y(-20)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(2)
        self.multi_cell(0, 4, 'Disclaimer: This report is generated by a deep-learning AI system (TumorVision v2.0). '
                            'It is intended for preliminary screening and research assistance only. '
                            'Final clinical diagnosis must be performed by a board-certified neuroradiologist.', 0, 'C')
        self.ln(2)
        self.cell(0, 5, f'Page {self.page_no()}', 0, 0, 'C')

def add_patient_info(pdf, original_filename, study_type):
    report_id = str(uuid.uuid4())[:8].upper()
    date_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    
    # Table Styling
    pdf.set_fill_color(248, 250, 252)
    pdf.set_draw_color(226, 232, 240)
    pdf.set_font('Arial', 'B', 10)
    
    # Row 1
    pdf.cell(35, 10, ' REPORT ID:', 1, 0, 'L', True)
    pdf.set_font('Arial', '', 10)
    pdf.cell(60, 10, f' TV-{report_id}', 1, 0, 'L')
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(35, 10, ' STUDY TYPE:', 1, 0, 'L', True)
    pdf.set_font('Arial', '', 10)
    pdf.cell(60, 10, f' {study_type}', 1, 1, 'L')
    
    # Row 2
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(35, 10, ' SOURCE FILE:', 1, 0, 'L', True)
    pdf.set_font('Arial', '', 10)
    pdf.cell(60, 10, f' {original_filename[:25]}', 1, 0, 'L')
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(35, 10, ' DATE/TIME:', 1, 0, 'L', True)
    pdf.set_font('Arial', '', 10)
    pdf.cell(60, 10, f' {date_str}', 1, 1, 'L')
    
    pdf.ln(10)

def generate_pdf_report_3d(metrics, img_path, original_filename, output_path):
    pdf = MedicalReport()
    pdf.add_page()
    
    # Brand Header
    pdf.set_font('Arial', 'B', 24)
    pdf.set_text_color(14, 165, 233) # Medical Blue
    pdf.cell(0, 15, 'TumorVision AI', 0, 1, 'L')
    pdf.set_font('Arial', '', 12)
    pdf.set_text_color(100)
    pdf.cell(0, 5, 'Automated Volumetric Segmentation Report', 0, 1, 'L')
    
    pdf.ln(8)
    add_patient_info(pdf, original_filename, "High-Res MRI Segmentation (3D)")
    
    # Volumetric Section
    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(30, 58, 138)
    pdf.cell(0, 10, 'Volumetric findings', 0, 1)
    pdf.set_draw_color(14, 165, 233)
    pdf.line(10, pdf.get_y(), 60, pdf.get_y())
    pdf.ln(5)
    
    # Metrics Table
    pdf.set_fill_color(241, 245, 249)
    pdf.set_draw_color(203, 213, 225)
    pdf.set_font('Arial', 'B', 10)
    pdf.set_text_color(51, 65, 85)
    
    pdf.cell(100, 10, " Anatomical Component", 1, 0, 'L', True)
    pdf.cell(90, 10, " Measured Volume (cm³)", 1, 1, 'L', True)
    
    pdf.set_font('Arial', '', 10)
    regions = [
        ("Enhancing Tumor Tissue", metrics.get('enhancing_cm3', 0), (220, 38, 38)),
        ("Peritumoral Edema", metrics.get('edema_cm3', 0), (202, 138, 4)),
        ("Necrotic / Cystic Core", metrics.get('necrotic_cm3', 0), (8, 145, 178)),
        ("Total Tumor Volume", metrics.get('total_volume_cm3', 0), (0, 0, 0))
    ]
    
    for label, val, col in regions:
        pdf.set_text_color(51, 65, 85)
        pdf.cell(100, 10, f" {label}", 1)
        pdf.set_font('Arial', 'B', 10)
        pdf.set_text_color(*col)
        pdf.cell(90, 10, f" {val:,.3f}", 1, 1, 'C')
        pdf.set_font('Arial', '', 10)
        
    pdf.ln(10)
    
    # Image Section
    if img_path and os.path.exists(img_path):
        pdf.set_font('Arial', 'B', 14)
        pdf.set_text_color(30, 58, 138)
        pdf.cell(0, 10, 'Reference Cross-Section', 0, 1)
        pdf.ln(2)
        
        # Center the image
        img_w = 100
        x_pos = (210 - img_w) / 2
        pdf.image(img_path, x=x_pos, y=pdf.get_y(), w=img_w)
        pdf.set_y(pdf.get_y() + img_w + 5)
    
    # Conclusion
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(30, 58, 138)
    pdf.cell(0, 10, 'Automated Clinical Impression:', 0, 1)
    pdf.set_font('Arial', '', 10)
    pdf.set_text_color(71, 85, 105)
    impression = (
        "The automated segmentation pipeline has identified a multi-compartment mass. "
        "Significant volumes of enhancing tissue and peritumoral edema are noted. "
        "Reconstruction suggest localized anatomical distortion consistent with space-occupying lesions. "
        "Correlation with gadolinium-enhanced T1 and FLAIR sequences is recommended."
    )
    pdf.multi_cell(0, 6, impression)

    pdf.output(output_path)
    return output_path

def generate_pdf_report_2d(prediction_label, confidence, img_path, original_filename, output_path):
    pdf = MedicalReport()
    pdf.add_page()
    
    # Brand Header
    pdf.set_font('Arial', 'B', 24)
    pdf.set_text_color(14, 165, 233)
    pdf.cell(0, 15, 'TumorVision AI', 0, 1, 'L')
    pdf.set_font('Arial', '', 12)
    pdf.set_text_color(100)
    pdf.cell(0, 5, 'Automated Screening & Classification Result', 0, 1, 'L')
    
    pdf.ln(8)
    add_patient_info(pdf, original_filename, "Rapid MRI Classification (2D)")
    
    # Findings Section
    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(30, 58, 138)
    pdf.cell(0, 10, 'Diagnostic Summary', 0, 1)
    pdf.set_draw_color(14, 165, 233)
    pdf.line(10, pdf.get_y(), 60, pdf.get_y())
    pdf.ln(5)
    
    # Main Result Card
    pdf.set_fill_color(248, 250, 252)
    pdf.set_draw_color(226, 232, 240)
    pdf.rect(10, pdf.get_y(), 190, 25, 'FD')
    
    pdf.set_y(pdf.get_y() + 5)
    pdf.set_x(15)
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(100)
    pdf.cell(50, 15, "CLASSIFIED TYPE:", 0, 0)
    
    # Status Color
    if "no tumor" in prediction_label.lower():
         pdf.set_text_color(22, 163, 74) # Green
    else:
         pdf.set_text_color(220, 38, 38) # Red
         
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(70, 15, prediction_label.upper(), 0, 0)
    
    pdf.set_text_color(100)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(35, 15, "CONFIDENCE:", 0, 0)
    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(30, 58, 138)
    pdf.cell(30, 15, f"{confidence}", 0, 1)
    
    pdf.ln(10)
    
    # Reference Image
    if img_path and os.path.exists(img_path):
        pdf.set_font('Arial', 'B', 12)
        pdf.set_text_color(30, 58, 138)
        pdf.cell(0, 10, 'Reference Image Analysis', 0, 1)
        pdf.ln(2)
        img_w = 90
        x_pos = (210 - img_w) / 2
        pdf.image(img_path, x=x_pos, y=pdf.get_y(), w=img_w)
        pdf.set_y(pdf.get_y() + img_w + 10)
    
    # Clinical Interpretation
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(30, 58, 138)
    pdf.cell(0, 10, 'AI Preliminary Interpretation:', 0, 1)
    pdf.set_font('Arial', '', 10)
    pdf.set_text_color(71, 85, 105)
    
    if "no tumor" in prediction_label.lower():
        msg = ("The neural ensemble did not identify high-risk morphological features consistent with common "
               "brain malignancies in the submitted slice. This does not rule out micro-pathologies or "
               "lesions outside the scanned plane. Regular clinical follow-up is advised.")
    else:
        msg = (f"The deep learning analysis has flagged high-confidence features associated with {prediction_label}. "
               "The identified structural patterns require immediate radiological correlation. "
               "Differential diagnosis should include metabolic, infectious, and neoplastic etiologies.")
        
    pdf.multi_cell(0, 6, msg)
    
    pdf.output(output_path)
    return output_path
